name: Continuous Release
on:
  push:
    branches:
      - master
jobs:
  create-zip:
    runs-on: ubuntu-latest
    if: "contains(github.event.head_commit.message, 'release')"
    steps:
      - uses: actions/checkout@v3
      - run: mkdir .zip
      - run: for i in */; do zip -r ."/.zip/${i%/}_Zeugnisse.$(date +'%d-%m-%Y').${{ github.run_number }}.zip" "$i" *.pdf; done
      - uses: ncipollo/release-action@v1.13.0
        with:
          artifacts: "./.zip/*"
          allowUpdates: true
          tag: v1.0.${{ github.run_number }}
          token: ${{ secrets.GITHUB_TOKEN }}
